<?php
/**
 * ItemInfoAutoloadTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Автозагрузка
 *
 * Получение отчётов о публикации и редактировании объявлений через Автозагрузку **Авито API для бизнеса предоставляется согласно [Условиям использования](https://api.avito.ru/docs/public/APITermsOfServiceV1.pdf).** <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1
 * Contact: supportautoload@avito.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ItemInfoAutoloadTest Class Doc Comment
 *
 * @category    Class
 * @description ItemInfoAutoload
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ItemInfoAutoloadTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ItemInfoAutoload"
     */
    public function testItemInfoAutoload()
    {
    }

    /**
     * Test attribute "alarm"
     */
    public function testPropertyAlarm()
    {
    }

    /**
     * Test attribute "applied_vas"
     */
    public function testPropertyAppliedVas()
    {
    }

    /**
     * Test attribute "avito_id"
     */
    public function testPropertyAvitoId()
    {
    }

    /**
     * Test attribute "errors"
     */
    public function testPropertyErrors()
    {
    }

    /**
     * Test attribute "event_time"
     */
    public function testPropertyEventTime()
    {
    }

    /**
     * Test attribute "fee_info"
     */
    public function testPropertyFeeInfo()
    {
    }

    /**
     * Test attribute "processing_time"
     */
    public function testPropertyProcessingTime()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "status_detail"
     */
    public function testPropertyStatusDetail()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "warnings"
     */
    public function testPropertyWarnings()
    {
    }
}
