<?php
/**
 * ReportCollectionAutoloadInnerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Автозагрузка
 *
 * Получение отчётов о публикации и редактировании объявлений через Автозагрузку **Авито API для бизнеса предоставляется согласно [Условиям использования](https://api.avito.ru/docs/public/APITermsOfServiceV1.pdf).** <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1
 * Contact: supportautoload@avito.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.32
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ReportCollectionAutoloadInnerTest Class Doc Comment
 *
 * @category    Class
 * @description ReportCollectionAutoloadInner
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReportCollectionAutoloadInnerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ReportCollectionAutoloadInner"
     */
    public function testReportCollectionAutoloadInner()
    {
    }

    /**
     * Test attribute "export_success"
     */
    public function testPropertyExportSuccess()
    {
    }

    /**
     * Test attribute "finished_at"
     */
    public function testPropertyFinishedAt()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "import_success"
     */
    public function testPropertyImportSuccess()
    {
    }

    /**
     * Test attribute "report_status"
     */
    public function testPropertyReportStatus()
    {
    }

    /**
     * Test attribute "started_at"
     */
    public function testPropertyStartedAt()
    {
    }

    /**
     * Test attribute "stat"
     */
    public function testPropertyStat()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }
}
